### PR TITLE
Fix #216 - Location dialog being triggered multiple times

### LINKED ISSUE #216: Info dialog for location permission is triggered twice
### Steps to reproduce

1. Start with a clean install.
2. Add the current location.
3. Tap on it.
4. The dialog informing about the request for location permissions is shown.
5. Switch to a different app or go to the home screen.
6. Go back into breezy weather.

### Expected behavior

The dialog is shown once.

### Actual behavior

The dialog is shown twice.

https://github.com/breezy-weather/breezy-weather/assets/97251923/5e2c76f6-8136-47f4-a7ae-f1311d2876fe

### Weather source used

N/A

### Breezy Weather version

4.3.0-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

This seems to be the only dialog where this happens. (API and resident city dialogs are not affected.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Help](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) documentation.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

### PR DESCRIPTION
**Pull request by ecawthorne**
As far as I can tell, what was happening here was that the activity was repeatedly creating new dialogs whenever the activity resumed from a pause. This should fix the issue by dismissing the existing dialogs on pauses instead. I'm fairly new to Kotlin, Compose, and android development as a whole so if there's a better way to handle this please let me know. Any feedback is appreciated!

### CODE REVIEW

**Comment by papjul** [comment]
Thank you!

I understand the fix but why did you remove the condition that was ensuring the dialog is shown only once?

**Comment by ecawthorne** [comment]
I misunderstood the intention behind that condition. Fixed in [079461a](https://github.com/breezy-weather/breezy-weather/pull/1214/commits/079461a0f6feeb4eaaa4bf1f2ffc338ebb47dc3b)

File: app/src/main/java/org/breezyweather/main/MainActivity.kt [hunk 1]
```diff
@@ -327,8 +334,7 @@ class MainActivity : GeoActivity(),
                         }
 
                         if (showLocationPermissionDialog && !viewModel.statementManager.isLocationPermissionDialogAlreadyShown) {
```
Comment (min7-i) [inline app/src/main/java/org/breezyweather/main/MainActivity.kt:336]: Instead of dismissing the dialog in `onPause`, wouldn't it be easier to add a new condition `dialogPerLocationAlert == null` in the `if` statement, so the dialog is only created once?

Comment (ecawthorne) [reply app/src/main/java/org/breezyweather/main/MainActivity.kt:336]: Unfortunately that doesn't seem to work when I test it. If the user pauses the app while the dialog is open and then resumes it, the dialog is bypassed and it jumps to requesting permissions. As far as I can tell it's because the activity is being recreated, but when the activity is *recreated* rather than created, that variable would no longer be null.

Comment (min7-i) [reply app/src/main/java/org/breezyweather/main/MainActivity.kt:336]: You're right. A nested `if` expression with that condition should work though.

```
if (showLocationPermissionDialog && !viewModel.statementManager.isLocationPermissionDialogAlreadyShown) {
    if (dialogPerLocationAlert == null) {
        ...
```

Comment (ecawthorne) [reply app/src/main/java/org/breezyweather/main/MainActivity.kt:336]: That does work. My only concern is that this method causes a memory leak when the orientation changes or the app is closed. Dismissing the dialog seems to avoid that issue.

Comment (min7-i) [reply app/src/main/java/org/breezyweather/main/MainActivity.kt:336]: Thanks for pointing that out. That also seems to be an issue in the current release. Your solution with dismissing the dialog does indeed solve that 👍 

While having a closer look at this, I also noticed that a similar issue occurs when the dialog for the background location permission is [shown](https://github.com/breezy-weather/breezy-weather/blob/dc1808121702f1bbc9cba527290b123232451fe8/app/src/main/java/org/breezyweather/main/MainActivity.kt#L536). As it's not directly related to #216, I'll probably just open a separate PR to fix this.

**Comment by papjul** [comment]
Could you make a single commit?

If you need help with Git, this should do the trick:
```
git reset --soft HEAD~2
git commit -m 'Fix #216 - Location dialog being triggered multiple times'
git push --force
```

Thanks!

**Comment by papjul** [comment]
Thank you!
