### PR TITLE
Edge-to-edge support

### LINKED ISSUE #128: Snackbar is partly behind navigation bar [Android 9]
### Steps to reproduce

This is probably only happening on older Android versions. I tested this on my LG G6 running Android 9.

1. Go to settings => appearance.
2. Change the app language.
3. A snackbar is displayed.

### Expected behavior

The entire snackbar should be displayed above the navigation bar.

### Actual behavior

The snackbar is partly behind the navigation bar which makes it tricky to tap on the action; in this case the restart action.

### Weather provider used

n/a

### Breezy Weather version

4.1.1-beta

### Android version

Android 9

### Device

LG G6

### Other details

On my Pixel 6a (Android 13) snackbars are properly displayed above the navigation bar.

I could reproduce this behavior in Geometric Weather on my LG.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

### PR DESCRIPTION
**Pull request by min7-i**
This implements the solution described in #1335: 
- Methods to go edge-to-edge, handle window insets and system bars are updated. 
- The root layout and any related layouts that are not used anymore are removed.
- Content is now extended behind the status bar, display cutouts and navigation bar while making sure that important elements (buttons, texts) are not covered by system bars.
- When 3-button navigation is used, the navigation bar has a shade which matches the theme except for the main screen where the shade is always dark on Android 10 and newer.<sup>[1]</sup> ~~On Android 10 and newer the navigation bar is always transparent except for the main screen.~~ On older Android versions the navigation bar always has a dark shaded background.

#### Special Cases
- Location list (management fragment): content is not drawn behind the navigation bar as this shortly changes the navigation bar's color when overscrolling.
- Main screen (home fragment) in landscape mode:
    - insets are always applied for system bars. This seems to be the best solution for now as there a many different cases (devices w/o display cutouts). Any approach where content would be drawn behind system bars would require dynamic **and properly animated** adjustments of the insets when the drawer state (opened/closed) changes.
    - horizontal display cutouts in portrait mode are ignored. This is probably only affecting a few tablets with a display cutout when used in portrait mode ([left notch](https://github.com/user-attachments/assets/8a5b65c5-05b1-41b6-8fc5-82da8fb6291b), [right notch](https://github.com/user-attachments/assets/8894bbd7-87ac-4a3a-a6a5-c1eaf2209074)).

This also fixes #128 and #717.

### Testing
Successfully tested on the following devices:
- [x] Google Pixel 6a (Android 14) with gesture & 3-button navigation
- [x] LG G6 (Android 9) with 3-button navigation
- [x] Samsung Galaxy S24 (Android 14) with gesture & 3-button navigation [via Samsung Remote Test Lab]
- [x] Samsung Tab S9 (Android 14) with gesture & 3-button navigation [via Samsung Remote Test Lab]
- [x] Tablet emulated (Android 14)
- [x] Tablet emulated (Android 9) with 3-button navigation
- [x] Phone emulated (Android 5) with 3-button navigation

<details>

<summary>Test Cases</summary>

| Test | Area | Expected Result |
| --- | --- | --- |
| snackbar (landscape mode) | main screen, settings | The snackbar is as wide as the screen minus the system bars. (examples: [location list](https://github.com/user-attachments/assets/4156a2d2-db76-427c-9a95-8609fe51e5d9), [settings left](https://github.com/user-attachments/assets/191cef05-f22b-4cc5-8649-0289f6ca7c6c), [settings right](https://github.com/user-attachments/assets/c0906609-3d68-4d9e-82c0-4d6edf3dbd4f), [widget config](https://github.com/user-attachments/assets/129fe1c1-b537-4390-82d6-dde11d46df32)) |
| snackbar (portrait mode) | main screen, settings | The snackbar is shown above the navigation bar. (examples: [location list](https://github.com/user-attachments/assets/5416ee47-92e4-4392-b057-47d39e5bb3e0), [main](https://github.com/user-attachments/assets/e8975a6d-b8df-411e-ad01-0a08afda9bce), [settings](https://github.com/user-attachments/assets/af0ada85-9c1f-4a1d-9ccf-8602c8de4c05), [widget config](https://github.com/user-attachments/assets/131e9c5c-2d5a-4a4e-9709-cd361a84caf7)) |
| content (safe drawing) | search results, settings | Important elements (e.g. texts, buttons) are not hidden by the navigation bar or display cutouts. |
| location list (landscape mode) | location list | The location list does not have any left or right insets. (examples: [drawer layout landscape](https://github.com/user-attachments/assets/1954a93c-d52d-4f48-9e07-b99027d6b8f8)) |
| weather details insets | daily weather details | The  insets for the pager are set correctly. (examples: [daily details portrait](https://github.com/user-attachments/assets/800149d3-e536-4836-95ee-6391879b3e03), [daily details landscape](https://github.com/user-attachments/assets/8eef2b89-8123-4b0f-89b1-9fe421912f2e)) |
| bottom element | 	main screen, daily weather details, alerts, pollen, search results, location list, settings, icon preview, manage display list (cards, daily forecast, hourly forecast, header details) | The bottom element in a layout is not covered by the navigation bar. (examples: [alerts portrait](https://github.com/user-attachments/assets/25a2cca0-ba44-474c-985d-b227476b97fd), [main bottom portrait](https://github.com/user-attachments/assets/e94071f5-cba8-4237-9c2c-3b0aef6bde5a), [pollen portrait](https://github.com/user-attachments/assets/4ef0491f-15d4-4be9-b512-e5c112c51819), [search results portrait](https://github.com/user-attachments/assets/46257a5f-e570-461a-a5d4-008c463e33bf) - [alerts landscape](https://github.com/user-attachments/assets/740355ee-3fc2-48a1-a411-c3e4f468918c), [pollen landscape](https://github.com/user-attachments/assets/40049c6e-cc93-48b9-aeb8-86fd6ba8e274), [search input landscape](https://github.com/user-attachments/assets/3daa53f7-9ad2-4bbb-ab97-9bf3675ad1cc), [search results landscape](https://github.com/user-attachments/assets/3f2f1dff-f2ee-43ab-a10f-8572a0ec2bd1)) |
| theme changes | settings | Changing the theme in settings correctly sets the color of the system bars as described below. The system bars do not have a solid color. |

**Additional screenshots (gesture navigation)**
| orientation | screenshots |
| --- | --- |
| landscape | [alerts_landscape](https://github.com/user-attachments/assets/0ce26144-6826-4376-8a4b-30432e1ba286), [daily_landscape](https://github.com/user-attachments/assets/2ff5cb12-1507-45e3-8d4d-a0e500625944), [main_landscape](https://github.com/user-attachments/assets/b8400c11-c2fa-4f90-b892-cd4ba062699f), [pollen_landscape](https://github.com/user-attachments/assets/058b513b-ae1d-42c6-92e3-3361968da988), [snackbar_main_landscape](https://github.com/user-attachments/assets/7525bc8f-d016-4c25-9d2d-7351eb0a1178), [snackbar_settings_landscape](https://github.com/user-attachments/assets/0077586f-2488-4a02-a906-525e792ab884), [snackbar_widget_config_landscape](https://github.com/user-attachments/assets/9d41c80c-d458-4ab2-80ea-dab4dfca4fa3) |
| portrait | [alerts_portrait](https://github.com/user-attachments/assets/e08c5f5e-492b-4585-955c-ba9538e76847), [daily_portrait](https://github.com/user-attachments/assets/1a3dcbd4-54b1-40bc-8e06-aa5da9020d53), [main_portrait](https://github.com/user-attachments/assets/cbed673a-d3d4-4d3e-83ce-3117e0d6b327), [pollen_portrait](https://github.com/user-attachments/assets/2a875d07-1905-4001-a648-659d7bbbb15d), [snackbar_main_portrait](https://github.com/user-attachments/assets/587984ed-adc8-4d96-a789-bf2d778e5e3b), [snackbar_settings_portrait](https://github.com/user-attachments/assets/c78ef75a-c670-411c-8313-084a7a3bfcca), [snackbar_widget_config_portrait](https://github.com/user-attachments/assets/98667768-4db2-424a-a367-de773cb3e98c) |

#### Android >= 10
| Test | Expected Result |
| --- | --- |
| status bar (main screen) | The status bar is shaded when scrolling up on the main screen. |
| status bar background color | The background is transparent. |
| status bar foreground color | The foreground is light in dark mode and dark in light mode. |
| navigation bar (main screen) | The navigation bar is shaded on the main screen.<sup>[*]</sup> |
| navigation bar color | The navigation bar has a shade matching the theme (light shade for light theme, dark shade for dark theme).<sup>[*]</sup> |

[*] When gesture navigation is used, the navigation bar is always transparent; at least on stock Android. There might be some exceptions depending on the manufacturer.

#### Android <= 9
| Test | Expected Result |
| --- | --- |
| navigation bar | The navigation bar always has a dark shade with a light foreground. |

</details>

----

[1] After testing the changes on other devices I noticed that a transparent navigation bar has some contrast issues (transparent 
[1](https://github.com/user-attachments/assets/0e9e3b59-1f8f-4e15-ac9d-2ec6dec2f021), [2](https://github.com/user-attachments/assets/625cc357-876f-49ab-8f25-996913285b14); shaded [1](https://github.com/user-attachments/assets/eda3689a-f452-42b3-9660-0d3701fbbe0f), [2](https://github.com/user-attachments/assets/62ef0b80-736a-4c15-a771-feb63b4f3ffe)), especially on tablets which have a taskbar. As a result, I decided to keep the shade when 3-button navigation is used.

### CODE REVIEW

File: app/src/main/java/org/breezyweather/BreezyWeather.kt [hunk 1]
```diff
@@ -118,14 +122,29 @@ class BreezyWeather : Application(),
...
         }
     }
 
+    private fun updateDayNightMode(dayNightMode: Int) {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
+            // Sets and persists the night mode setting for this app. This allows the system to know
+            // if the app wants to be displayed in dark mode before it launches so that the splash
+            // screen can be displayed accordingly.
+            ContextCompat.getSystemService(getApplication(this), UiModeManager::class.java)
+                ?.setApplicationNightMode(
```
Comment (min7-i) [inline app/src/main/java/org/breezyweather/BreezyWeather.kt:138]: This fixes the follwing issues:
- On newer Android version a theme change would not immediately be applied in the location list (management fragment).
- With targetSDK/compileSDK 35 a theme change would cause the system bars to have a solid color.

Additionally, this is a prerequisite for #137.

File: app/src/main/java/org/breezyweather/main/fragments/ManagementFragment.kt [hunk 2]
```diff
@@ -278,7 +291,7 @@ open class ManagementFragment : MainModuleFragment(), TouchReactor {
                     }
                     AndroidView(
                         modifier = Modifier
-                            .fillMaxHeight()
+                            .fillMaxSize()
```
Comment (min7-i) [inline app/src/main/java/org/breezyweather/main/fragments/ManagementFragment.kt:294]: This fixes an issue where the items (locations) in the location list aren't consuming the entire width in landscape mode when the navigation bar is hidden ([issue](https://github.com/user-attachments/assets/49871cf9-d0c9-4401-900f-04fab15794d9), [fix](https://github.com/user-attachments/assets/d2f717b6-0e43-4562-8712-02cf4ce10b03)).

File: app/src/main/java/org/breezyweather/remoteviews/config/AbstractWidgetConfigActivity.kt [hunk 3]
```diff
@@ -189,11 +188,6 @@ abstract class AbstractWidgetConfigActivity : GeoActivity() {
             initView()
             updateHostView()
         }
-    }
-
-    override fun onPostCreate(savedInstanceState: Bundle?) {
-        super.onPostCreate(savedInstanceState)
-
         KeyboardResizeBugWorkaround.assistActivity(this)
```
Comment (min7-i) [inline app/src/main/java/org/breezyweather/remoteviews/config/AbstractWidgetConfigActivity.kt:191]: Moving this into `onCreate` fixes an issue where the window insets are only correctly applied after tapping into the text input field for the custom subtitle ([issue](https://github.com/user-attachments/assets/2284d638-a65e-4c54-a172-6901c02bbdd2), [fix](https://github.com/user-attachments/assets/1ea4e40c-c992-4957-946d-9ef43e6f88b1)).

File: app/src/main/java/org/breezyweather/main/fragments/HomeFragment.kt [hunk 4]
```diff
@@ -191,14 +209,29 @@ class HomeFragment : MainModuleFragment() {
             Color.WHITE, PorterDuff.Mode.SRC_ATOP
         )
 
+        // Align refreshTimeText with toolbar (some devices, e.g. tablets, have an additional
+        // start padding).
+        (binding.refreshTimeText.layoutParams as ViewGroup.MarginLayoutParams).apply {
+            marginStart = binding.toolbar.paddingStart + requireContext()
+                .resources.getDimensionPixelSize(R.dimen.normal_margin)
+        }
```
Comment (min7-i) [inline app/src/main/java/org/breezyweather/main/fragments/HomeFragment.kt:217]: This fixes the alignment of the refresh time text and the topAppBar (drawer icon) on tablets ([issue](https://github.com/user-attachments/assets/3d5e67d3-e278-487f-9fe2-9fff457c48dc), [fix](https://github.com/user-attachments/assets/c4d98c27-f165-4989-9476-9a66685cd40e)).

**Comment by min7-i** [comment]
This is ready for review now. I split the PR into multiple commits which, hopefully, makes it a bit easier to understand the changes. I can squash the commits after the review though.

**Comment by min7-i** [comment]
Force-pushed to fix some comments.

**Comment by papjul** [comment]
Alright, LGTM, let's merge it on the `main` branch so everyone can test it before the next release ;)
