### PR TITLE
Fix #1291 Update surface colors

### LINKED ISSUE #1291: [v5.2.8] Theme issues
Since 2d7afa3eb899f29ba26099d0dd37c93ebc5f7589, there are theme issues.

It is observed in the location list:
1. Make a search
2. See wrong theme in results
3. Tap a result
4. See wrong theme again in dialog

### PR DESCRIPTION
**Pull request by ecawthorne**
Fixes #1291

It seems like this was happening due to [compose-material3 1.3](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.3.0) changing the surface default color slightly:

> Small adjustments to surface and background color defaults in lightColorScheme and darkColorScheme. ([I9db52](https://android-review.googlesource.com/#/q/I9db5226e26371223bc46f37ddfe226acf7767041))

I just used xcolor to match the new colors. I'm not sure if there's any available documentation on the palette they're using. This issue was affecting the edit location dialog and the notification time dialog as well.

### CODE REVIEW

**Comment by min7-i** [comment]
With [compose-material3 1.3.0](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.3.0-alpha02) the container color for [AlertDialog](https://android-review.googlesource.com/c/platform/frameworks/support/+/2954034/2/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/tokens/DialogTokens.kt) and [SearchBar](https://android-review.googlesource.com/c/platform/frameworks/support/+/2958192/2/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/tokens/SearchBarTokens.kt) was changed from `Surface` to `SurfaceContainerHigh` while [ListItem](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/tokens/ListTokens.kt;l=27) still uses `Surface`.

Instead of changing the color of `Surface` which also affects other areas, e.g. the background in settings, I'd suggest to adjust the `containerColor` of `ListItem` when it's used in a dialog or in the search composable. For the [SearchActivity](https://github.com/breezy-weather/breezy-weather/blob/000ea8d488e27dd95ab00100637ccfad7d15e235/app/src/main/java/org/breezyweather/search/SearchActivity.kt#L182) you could for instance pass a different color directly:
```
ListItem(
  colors = ListItemDefaults.colors(
      containerColor = SearchBarDefaults.colors().containerColor
  ),
  ...
```

For the dialog we'd probably have to update the preference composables that are used there and add a new parameter to modify the colors for the `ListItem`.

----

> I'm not sure if there's any available documentation on the palette they're using.

You can find the `PaletteTokens` [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/tokens/PaletteTokens.kt) via the Android Code Search. Alternatively, you should also be able to see the sources in Android Studio.

----

> This issue was affecting the edit location dialog and the notification time dialog as well.

I didn't notice any issues with the notification time dialog.

**Comment by ecawthorne** [comment]
Thank you for the clarification and advice! Both of your suggestions work. I'm not sure exactly what happened on my end but changing the surface colors doesn't seem to be working the way I thought it was regardless. I think I must have changed something unintentionally while testing.

> For the dialog we'd probably have to update the preference composables that are used there and add a new parameter to modify the colors for the ListItem.

Working on this now. There are a few more areas than I originally thought that are affected by this.

File: app/src/main/java/org/breezyweather/search/SearchActivity.kt [hunk 1]
```diff
@@ -18,7 +18,6 @@ package org.breezyweather.search
 
 import android.content.Intent
 import android.os.Bundle
-import android.window.OnBackInvokedDispatcher
```
Comment (ecawthorne) [inline app/src/main/java/org/breezyweather/search/SearchActivity.kt:21]: This is inherited by the activity so it was unused. I can revert this change if it's something you want done here since it's not related to this particular pull request.

File: app/src/main/java/org/breezyweather/settings/compose/WeatherSourcesSettingsScreen.kt [hunk 2]
```diff
@@ -105,17 +107,18 @@ fun WeatherSourcesSettingsScreen(
 
             sectionHeaderItem(R.string.settings_weather_sources_section_general)
             listPreferenceItem(R.string.settings_weather_sources_default_source) { id ->
-        val configuredWorldwideSourcesAssociated = configuredWorldwideSources.associate { it.id to it.name }
+                val configuredWorldwideSourcesAssociated = configuredWorldwideSources.associate { it.id to it.name }
                 val defaultWeatherSource = SettingsManager.getInstance(context).defaultWeatherSource
                 SourceView(
                     title = stringResource(id),
-            selectedKey = if (configuredWorldwideSourcesAssociated.contains(defaultWeatherSource)) {
```
Comment (ecawthorne) [inline app/src/main/java/org/breezyweather/settings/compose/WeatherSourcesSettingsScreen.kt:112]: Just indentation fixes. Can revert if needed.

File: app/src/main/java/org/breezyweather/sources/openmeteo/OpenMeteoService.kt
Comment (min7-i) [inline app/src/main/java/org/breezyweather/sources/openmeteo/OpenMeteoService.kt:1]: The `SwitchPreferenceView` composable also needs the new `colors` parameter because it's used [here](https://github.com/breezy-weather/breezy-weather/pull/1293/files#diff-f16bf38459bba0fe0b230b1b281bd0a94ba6e1ac6d410c49b4b097e3ab090261L491) in a dialog.

Comment (ecawthorne) [reply app/src/main/java/org/breezyweather/sources/openmeteo/OpenMeteoService.kt:1]: Fixed in the latest commit. I thought I had caught that one, thank you for noticing.

File: app/src/main/java/org/breezyweather/settings/preference/composables/SwitchPreference.kt [hunk 3]
```diff
@@ -84,6 +89,7 @@ fun SwitchPreferenceView(
     withState: Boolean = true,
     enabled: Boolean = true,
     card: Boolean = true,
+    colors: ListItemColors = ListItemDefaults.colors(AlertDialogDefaults.containerColor),
```
Comment (min7-i) [inline app/src/main/java/org/breezyweather/settings/preference/composables/SwitchPreference.kt:92]: The default here should also be `ListItemDefaults.colors()` in my opinion.

File: app/src/main/java/org/breezyweather/settings/preference/composables/ListPreference.kt [hunk 4]
```diff
@@ -117,6 +122,7 @@ fun ListPreferenceView(
             elevation = if (enabled) defaultCardListItemElevation else 0.dp
         ) {
             ListItem(
+                colors = colors,
```
Comment (min7-i) [inline app/src/main/java/org/breezyweather/settings/preference/composables/ListPreference.kt:125]: I don't think it makes sense to add `colors` here as the background color of the card will be different from the one used for the list item. Currently, we don't have any issues with the card version of the preference composables so I'd leave it as-is for now.

The same applies to the [PreferenceView](https://github.com/breezy-weather/breezy-weather/pull/1293/files#diff-323f5c2cc2ba1e2d29d8c3e066af6601ab0a3575b232dd34cfe377f02192803dL91).

Removing that would also remove the need to pass `colors` in [WeatherSourcesSettingsScreen](app/src/main/java/org/breezyweather/settings/compose/WeatherSourcesSettingsScreen.kt).

Comment (ecawthorne) [reply app/src/main/java/org/breezyweather/settings/preference/composables/ListPreference.kt]: Makes sense to me. Changes in the latest commit.

File: app/src/main/java/org/breezyweather/settings/preference/composables/SwitchPreference.kt (hunk 3 above)
Comment (ecawthorne) [reply app/src/main/java/org/breezyweather/settings/preference/composables/SwitchPreference.kt]: Agreed. Changes in latest commit.

**Comment by min7-i** [comment]
Thanks! LGTM

**Comment by ecawthorne** [comment]
Sorry for the extra CI runs, commit history should be clean now.

**Comment by papjul** [comment]
Thanks, both of you
