### PR TITLE
Fix theme issues in AlertActivity and PollenActivity

### LINKED ISSUE #1138: Alerts screen: Theme is applied from 06:00 to 18:00 regardless of sunset time
### Steps to reproduce

1. Make sure "enable day/night for locations" is enabled
2. Add a location with active weather alerts whose timezone is after 18:00 but before sunset
3. Click on the alerts

### Expected behavior

Alerts screen should be light theme in line with cards

### Actual behavior

Alerts screen is dark

### Weather source used

N/A

### Breezy Weather version

5.2.4 standard

### Android version

12

### Device

Samsung Galaxy s10e

### Other details

Compare: Paris before 18:00, Paris after 18:00

Screenshot_20240614-184240_Breezy Weather
Screenshot_20240614-184248_Breezy Weather
Screenshot_20240614-190641_Breezy Weather
Screenshot_20240614-190649_Breezy Weather

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

### PR DESCRIPTION
**Pull request by min7-i**
This fixes #1138 by retrieving the weather data for the location to calculate the correct "[rise progress](https://github.com/breezy-weather/breezy-weather/blob/d59725585c518ca48e079ead6b6ac3bb29b36183/app/src/main/java/org/breezyweather/domain/weather/model/Astro.kt#L18)" of the sun. Previously it used defaults (sunrise at 6 am, sunset at 6 pm) as a fallback which caused the issue described in #1138.

The PR also fixes an issue with the color of the status bar in the PollenActivity when the location-based day/night mode is enabled. It now uses the same approach as PR #1022.

Tested on devices with Android 9 and 14.

<details>

<summary>screenshots</summary>

Tested with locations where the sun was still up. Location-based day/night mode was enabled and the dark theme was used in the app.

| location | old | new |
| --- | --- | --- |
| Beijing | alert_1 | alert_2 |
| Hamburg | pollen_1 | pollen_2 |

</details>

### CODE REVIEW

File: app/src/main/java/org/breezyweather/common/ui/activities/AlertActivity.kt [hunk 1]
```diff
@@ -133,7 +133,18 @@ class AlertActivity : GeoActivity() {
...
+
+            // Astro data is needed to check if the sun is still up or if it has set when day/night
+            // mode per location is enabled.
+            location.value = locationC.copy(
+                weather = weatherRepository.getWeatherByLocationId(
+                    locationC.formattedId,
+                    withDaily = true,
+                    withHourly = false,
+                    withMinutely = false,
+                    withAlerts = false
```
Comment (papjul) [inline app/src/main/java/org/breezyweather/common/ui/activities/AlertActivity.kt:145]: Maybe we should take this opportunity to refactor and use `withAlerts = true` and remove the second query of alerts later.

Comment (min7-i) [reply app/src/main/java/org/breezyweather/common/ui/activities/AlertActivity.kt]: Thanks for the hint. I updated the PR accordingly.
