### PR TITLE
Fix #136 - disable animation settings when disabled at system level

### LINKED ISSUE #136: Animation preferences in Home screen settings are available to configure even if user disabled Animations at Android level
### Steps to reproduce

As title says.

### Expected behavior

Settings should be disabled and a toast message should be show if user tap on the card explaining it’s because they disable animations in Android settings.

### Actual behavior

Preferences can be switched on but none of them will work.

### Weather provider used

Not relevant

### Breezy Weather version

4.1.1-beta

### Android version

Not relevant

### Device

Not relevant

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

### PR DESCRIPTION
**Pull request by ecawthorne**
~~As a heads up, merging this will likely open up a new issue. After fixing this, I noticed another bug where disabling animations in the app doesn't override individual animations e.g. If you disable all animations without also disabling cards fading in those animations will still play.~~ Disregard

### CODE REVIEW

File: app/src/main/java/org/breezyweather/settings/compose/MainScreenSettingsScreen.kt [hunk 1]
```diff
@@ -157,12 +158,26 @@ fun MainScreenSettingsScreen(
                     },
                 )
             }
+
+            val animationsEnabled = !context.isMotionReduced
+                    && (SettingsManager.getInstance(context).backgroundAnimationMode
+                    != BackgroundAnimationMode.DISABLED)
```
Comment (papjul) [inline app/src/main/java/org/breezyweather/settings/compose/MainScreenSettingsScreen.kt:164]: The second condition will disable cards fade in and other elements which are unrelated to the background animation. Was not part of #136 but makes sense for "gravity sensor" though

File: app/src/main/res/values/strings.xml [hunk 2]
```diff
@@ -641,6 +641,7 @@
     <string name="settings_enabled">Enabled</string>
     <string name="settings_disabled">Disabled</string>
     <string name="settings_unavailable_no_background_updates">Unavailable, enable background updates first</string>
+    <string name="settings_unavailable_no_animations">Unavailable, enable animations here and in system settings first</string>
```
Comment (papjul) [inline app/src/main/res/values/strings.xml:644]: This needs to be adjusted following the change requested above

File: app/src/main/java/org/breezyweather/settings/compose/MainScreenSettingsScreen.kt (hunk 1 above)
Comment (ecawthorne) [reply app/src/main/java/org/breezyweather/settings/compose/MainScreenSettingsScreen.kt:164]: If the system settings are going to override the app settings, would it make sense to change this into a `switchPreferenceItem`? And then just disable it in the same way if the system animations are disabled? 

It might be more intuitive because that way if animations are enabled system wide the user can either enable or disable them for the app, but if they're disabled system wide the button is also disabled. Having a "follow system" option is somewhat redundant if the user can't enable the option if it's disabled by the system. 

I'll change the other options back to the way they were in the next commit and create a new issue / pull request for them once this is merged.

Comment (min7-i) [reply app/src/main/java/org/breezyweather/settings/compose/MainScreenSettingsScreen.kt:164]: > If the system settings are going to override the app settings, would it make sense to change this into a switchPreferenceItem?

You're talking about the preference for the background animation, right? Currently, the system setting for reduced motion [is only considered](https://github.com/breezy-weather/breezy-weather/blob/a89133c38e3e386f8a189c064fdd41dcd71a002e/app/src/main/java/org/breezyweather/main/fragments/HomeFragment.kt#L112) when the background animation is set to `BackgroundAnimationMode.SYSTEM`. If it is set to `BackgroundAnimationMode.ENABLED`, the system setting is ignored and the background is animated.

By the way, the gravity sensor animation [doesn't adhere](https://github.com/breezy-weather/breezy-weather/blob/a89133c38e3e386f8a189c064fdd41dcd71a002e/app/src/main/java/org/breezyweather/main/fragments/HomeFragment.kt#L169) to the system setting right now. With this change the preference composable would be disabled when reduced motion is active while the gravity sensor animation itelf would still be running by default. _(Some static backgrounds like partly cloudy still have animated elements controlled by the gravity sensor.)_

Comment (ecawthorne) [reply app/src/main/java/org/breezyweather/settings/compose/MainScreenSettingsScreen.kt:164]: I am. I'll revert the changes to every other option besides the background animation option in the next commit. The linked issue implies that the system settings should take priority over the app settings for background animations. If that's not an inference I should be making please let me know.

Comment (ecawthorne) [reply app/src/main/java/org/breezyweather/settings/compose/MainScreenSettingsScreen.kt]: > The second condition will disable cards fade in and other elements which are unrelated to the background animation. Was not part of #136 but makes sense for "gravity sensor" though

This may be a change for another pull request, but the card fade in also currently tracks the `Context.isMotionReduced` setting in the same way the background animations do. I'm not sure if that's intended or not though. If it is intended should that card behave the same way as the background animations card does? If it's not intended should I create a new issue for it?

**Comment by min7-i** [comment]
Before doing any partial changes, it might be easier to go a step back and evaluate the current situation:
- Which animation settings actually follow the reduced motion setting?
- Are any changes to the current behavior required or is everything working as expected?

Then it should be clearer which preference composables can be disabled when reduced motion is enabled.

**Comment by ecawthorne** [comment]
As far as I can tell the only setting that does _not_ follow the reduced motion setting is the gravity sensor. Background animations and the card fade setting follow the system settings regardless of whether they are enabled in the app itself or not. I don't know the intended behavior for these settings so I don't think I can address your second bullet point unfortunately.

**Comment by min7-i** [comment]
I can confirm your results except for the background animations. As mentioned in [this comment](https://github.com/breezy-weather/breezy-weather/pull/1219#discussion_r1690390999), it only follows the system setting when set to `SYSTEM`. (If you change the reduced motion setting while the app is running, it requires an app restart.)

Regarding your suggestion to change this to a switch preference: This would entail a few other changes. We'd have to migrate existing users who set the mode to `SYSTEM` and we'd have to update the value used as a default value for a fresh install. Keeping `SYSTEM` as the default would allow users who have reduced motion enabled to manually enable background animations; not sure if that's a much used feature. All in all, I'm wondering if it's worth the effort to make any changes here.

Coming back to #136, in my opinion the goal is to disable the preference composables which do not overwrite the reduced motion setting when it is enabled. In the current state this would only affect the composables for 'card fade in' and 'other element animations'.

What are your thoughts on this, @papjul?

**Comment by papjul** [comment]
I’m sorry, I got a bit lost in the discussion and I said wrong things previously.

Let’s take a look at the current situation:

|                        | Animations disabled | Animations enabled |
|------------------------|---------------------|--------------------|
| Gravity sensor enabled | ✅                   | ✅                  |
| Cards fade in enabled  | ❌                   | ✅                  |
| Other elements enabled | ❌                   | ✅                  |

So the issue #136 is about disabling options "Cards fade in" and "Other elements" when animations are disabled because it will NEVER work in this context. This is different than "Background animation" which can be forced to work even if user disabled animations at system level (which is why we have this follow system/enabled/disabled choice).

So for "Cards fade in" and "Other elements" preferences WHEN animations are disabled, this is what we expect:
- `enabled = false`
- `checked = false`
- `summaryOff = Unavailable, enable animations in Android settings first`

Regarding "Gravity sensor", we can leave it untouched or do the same thing we did for "Background animation", but for this PR, please leave it untouched. If this is important to you, you can open a discussion-idea and we will discuss it further.

Hopes this is clearer and I didn’t miss anything this time.

**Comment by ecawthorne** [comment]
I think I was able to make the requested changes, but if there are any issues or other changes that need to be made just let me know. I'm not too familiar with this git workflow so if there are any issues with the commit history just let me know on that front as well. Thank you for the feedback otherwise!

**Comment by papjul** [comment]
LGTM, let me know what you think @min7-i

**Comment by min7-i** [comment]
LGTM 👍
